# Generated by Django 5.1 on 2024-09-09 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='m_user',
        ),
    ]
