FROM node:20

WORKDIR /app

COPY package*.json ./

RUN npm install
RUN npm uninstall consola
RUN npm install consola

ENV HOST 0.0.0.0

# 開発環境用
ENV CHOKIDAR_USEPOLLING=true

EXPOSE 3000

# 開発環境用
CMD [ "npm", "run", "dev" ]