# Generated by Django 5.1 on 2024-09-21 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rank_id',
            new_name='rank',
        ),
    ]
