# Generated by Django 5.1 on 2025-01-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_miss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
