# Generated by Django 5.1.6 on 2025-03-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_request_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='typing_count',
            field=models.IntegerField(default=0),
        ),
    ]
