# Generated by Django 5.1 on 2025-01-02 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mistype", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Miss",
        ),
    ]
