CREATE TABLE user_rank (
    rank_id INT AUTO_INCREMENT PRIMARY KEY,
    rank_name VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    del_flg BOOLEAN DEFAULT false
);